from tkinter import *
import formulas
from sys import *


def start():
    U = float(ent1.get())
    R = float(ent2.get())
    r = float(ent3.get())
    l = float(ent4.get())
    E = float(ent5.get())
    v0 = float(ent6.get()) * 10 ** 3
    window.quit()
    formulas.graph(U, R, r, l, E, v0)


window = Tk()
window.title("Ввод данных")
window.geometry('380x160')
lbl1 = Label(window, text="Напряжение между обкладками")
lbl1.grid(column=0, row=0)
lbl2 = Label(window, text="Радиус внешнего цилиндра")
lbl2.grid(column=0, row=1)
lbl3 = Label(window, text="Расстояние между обкладками")
lbl3.grid(column=0, row=2)
lbl4 = Label(window, text="Длина конденсатора")
lbl4.grid(column=0, row=3)
lbl5 = Label(window, text="Диэлектрическая проницаемость конденсатора")
lbl5.grid(column=0, row=4)
lbl6 = Label(window, text="Скорость электрона в начальный момент")
lbl6.grid(column=0, row=5)
ent1 = Entry(window, width=10)
ent1.grid(column=1, row=0)
ent2 = Entry(window, width=10)
ent2.grid(column=1, row=1)
ent3 = Entry(window, width=10)
ent3.grid(column=1, row=2)
ent4 = Entry(window, width=10)
ent4.grid(column=1, row=3)
ent5 = Entry(window, width=10)
ent5.grid(column=1, row=4)
ent6 = Entry(window, width=10)
ent6.grid(column=1, row=5)
lbl_1 = Label(window, text="В")
lbl_1.grid(column=2, row=0)
lbl_2 = Label(window, text="м")
lbl_2.grid(column=2, row=1)
lbl_3 = Label(window, text="м")
lbl_3.grid(column=2, row=2)
lbl_4 = Label(window, text="м")
lbl_4.grid(column=2, row=3)
lbl_5 = Label(window, text="Ф/м")
lbl_5.grid(column=2, row=4)
lbl_6 = Label(window, text="км/с")
lbl_6.grid(column=2, row=5)
ent1.insert(1, "50")
ent2.insert(1, "0.2")
ent3.insert(1, "0.15")
ent4.insert(1, "10")
ent5.insert(1, "3")
ent6.insert(1, "300000")
btn = Button(window, text="     Пуск     ", command=start)
btn.grid(column=1, row=6)
window.mainloop()
